import { supabase } from "@/integrations/supabase/client";

export type CloudinaryFolder =
  | "discover-posts"
  | "store-products"
  | "profile-images"
  | "banners"
  | "system-assets"
  | "product-stories";

export interface CloudinaryUploadResult {
  secure_url: string;
  public_id: string;
  width: number;
  height: number;
  format: string;
}

/**
 * Upload a file to Cloudinary using a signature generated by our edge function.
 * The original API secret never leaves the server.
 */
export async function uploadToCloudinary(
  file: File,
  folder: CloudinaryFolder
): Promise<CloudinaryUploadResult> {
  const { data, error } = await supabase.functions.invoke("cloudinary-sign", {
    body: { folder },
  });
  if (error || !data?.signature) {
    throw new Error(error?.message || "Failed to sign upload");
  }
  const { signature, timestamp, apiKey, cloudName } = data;

  const form = new FormData();
  form.append("file", file);
  form.append("api_key", apiKey);
  form.append("timestamp", String(timestamp));
  form.append("signature", signature);
  form.append("folder", folder);

  const res = await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`, {
    method: "POST",
    body: form,
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json?.error?.message || "Cloudinary upload failed");
  return json as CloudinaryUploadResult;
}

/** Detect Cloudinary URL and inject delivery transformations (f_auto, q_auto, w_X). */
export interface CldOptions {
  width?: number;
  height?: number;
  crop?: "fill" | "fit" | "limit" | "scale" | "thumb";
  gravity?: "auto" | "face" | "center";
  quality?: "auto" | number;
  blur?: number;
}

export function cldOptimize(url: string | null | undefined, opts: CldOptions = {}): string {
  if (!url) return "";
  // Only rewrite Cloudinary URLs.
  const match = url.match(/^(https?:\/\/res\.cloudinary\.com\/[^/]+\/image\/upload)\/(.+)$/);
  if (!match) return url;

  const [, base, rest] = match;
  // Strip any existing transformation segment between /upload/ and v123/...
  // Cloudinary transformation segments contain commas or known prefixes; we keep it simple
  // by stripping the segment before the version (v123) or public id.
  const parts = rest.split("/");
  // If the first segment looks like a transformation (has comma or known prefixes), drop it.
  if (parts.length > 1 && /^([a-z]_[^/,]+)(,[a-z]_[^/,]+)*$/.test(parts[0])) {
    parts.shift();
  }
  const cleanRest = parts.join("/");

  const t: string[] = ["f_auto", `q_${opts.quality ?? "auto"}`];
  if (opts.width) t.push(`w_${opts.width}`);
  if (opts.height) t.push(`h_${opts.height}`);
  if (opts.crop) t.push(`c_${opts.crop}`);
  if (opts.gravity) t.push(`g_${opts.gravity}`);
  if (opts.blur) t.push(`e_blur:${opts.blur}`);

  return `${base}/${t.join(",")}/${cleanRest}`;
}

/** Build a responsive srcSet for a Cloudinary URL. */
export function cldSrcSet(url: string, widths: number[] = [320, 480, 640, 960, 1280]): string {
  return widths.map((w) => `${cldOptimize(url, { width: w, crop: "limit" })} ${w}w`).join(", ");
}

/** Tiny low-quality placeholder URL (used as background blur). */
export function cldPlaceholder(url: string): string {
  return cldOptimize(url, { width: 32, quality: 30, blur: 400 });
}
